from auth_routes import *
from dashboard import *
from .material_routes import *
from .vendor_routes import *
from .store_routes import *
from .stock_routes import *
from .po_routes import *
from .movements_routes import *
from .user_routes import *
from .issue_routes import *